from app.admin_routes.admin_category_routes import *
from app.admin_routes.admin_paint_routes import *
from app.admin_routes.admin_procedure_routes import *
from app.admin_routes.admin_supply_routes import *
from app.admin_routes.admin_client_routes import *
from app.admin_routes.admin_master_routes import *
from app.admin_routes.admin_schedule_routes import *
from app.admin_routes.admin_appointment_routes import *
from app.admin_routes.admin_appointment_paint_routes import *
from app.admin_routes.admin_statisctics_routes import *
