"""procedure relevant nullable

Revision ID: 09683593d228
Revises: 8e2e7abeac3b
Create Date: 2020-06-10 17:57:11.719538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09683593d228'
down_revision = '8e2e7abeac3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure', sa.Column('is_relevant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure', 'is_relevant')
    # ### end Alembic commands ###
