"""Timestamp Schedule Change

Revision ID: 13e7aba191e0
Revises: 408e599d5164
Create Date: 2020-05-05 23:46:21.283226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e7aba191e0'
down_revision = '408e599d5164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_change', sa.Column('change_end', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('schedule_change', sa.Column('change_start', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_change', 'change_start')
    op.drop_column('schedule_change', 'change_end')
    # ### end Alembic commands ###
