"""Timestamp for appointment

Revision ID: 1b227c3ab210
Revises: 517196b686c7
Create Date: 2020-05-06 08:50:24.120615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b227c3ab210'
down_revision = '517196b686c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appoint_end', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('appointment', sa.Column('appoint_start', sa.TIMESTAMP(timezone=True), nullable=False))
    op.create_unique_constraint('unique_client_time', 'appointment', ['appoint_start', 'client_id'])
    op.create_unique_constraint('unique_master_time', 'appointment', ['appoint_start', 'master_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_master_time', 'appointment', type_='unique')
    op.drop_constraint('unique_client_time', 'appointment', type_='unique')
    op.drop_column('appointment', 'appoint_start')
    op.drop_column('appointment', 'appoint_end')
    # ### end Alembic commands ###
