"""Master info

Revision ID: 2ca08aca9845
Revises: ae362d85aa28
Create Date: 2020-06-10 12:02:35.166048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca08aca9845'
down_revision = 'ae362d85aa28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('info', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'info')
    # ### end Alembic commands ###
