"""MasterProcedure to Model

Revision ID: 328ecb2f2c6a
Revises: 4178da311d37
Create Date: 2020-05-01 15:21:41.764143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328ecb2f2c6a'
down_revision = '4178da311d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_procedure', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_procedure', 'duration')
    # ### end Alembic commands ###
