"""Client Master SC FM

Revision ID: 4c3834fa9d65
Revises: 17b9fc32377d
Create Date: 2020-04-22 11:13:08.781680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3834fa9d65'
down_revision = '17b9fc32377d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('fist_name', sa.String(length=20), nullable=False),
    sa.Column('second_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('is_male', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('fist_name', sa.String(length=20), nullable=False),
    sa.Column('second_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('even_schedule', sa.Boolean(), nullable=False),
    sa.Column('is_hired', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('favourite_master',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id', 'master_id')
    )
    op.create_table('schedule_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('schedule_change')
    op.drop_table('favourite_master')
    op.drop_table('master')
    op.drop_table('client')
    # ### end Alembic commands ###
