"""Removed time from appointment

Revision ID: 517196b686c7
Revises: 13e7aba191e0
Create Date: 2020-05-06 08:40:03.291469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '517196b686c7'
down_revision = '13e7aba191e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_client_time', 'appointment', type_='unique')
    op.drop_constraint('unique_master_time', 'appointment', type_='unique')
    op.drop_column('appointment', 'end_time')
    op.drop_column('appointment', 'start_time')
    op.drop_column('appointment', 'appoint_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appoint_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('appointment', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointment', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.create_unique_constraint('unique_master_time', 'appointment', ['start_time', 'master_id'])
    op.create_unique_constraint('unique_client_time', 'appointment', ['start_time', 'client_id'])
    # ### end Alembic commands ###
