"""Procedure uses paints nullable

Revision ID: 66cbc7ba4455
Revises: 2ca08aca9845
Create Date: 2020-06-10 12:15:56.859844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cbc7ba4455'
down_revision = '2ca08aca9845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure', sa.Column('uses_paints', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure', 'uses_paints')
    # ### end Alembic commands ###
