"""Procedure Category FP MP

Revision ID: 69379fc40c85
Revises: 4c3834fa9d65
Create Date: 2020-04-22 12:00:30.222773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69379fc40c85'
down_revision = '4c3834fa9d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('price_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('info', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favourite_procedure',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id', 'procedure_id')
    )
    op.create_table('master_procedure',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('master_id', 'procedure_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_procedure')
    op.drop_table('favourite_procedure')
    op.drop_table('procedure')
    op.drop_table('category')
    # ### end Alembic commands ###
