"""Procedure uses paints not nullable

Revision ID: 8e2e7abeac3b
Revises: 66cbc7ba4455
Create Date: 2020-06-10 12:17:04.747430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2e7abeac3b'
down_revision = '66cbc7ba4455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedure', 'uses_paints',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedure', 'uses_paints',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
