"""first name spelling correction

Revision ID: 967f8a6f84a6
Revises: 9c9ab138c396
Create Date: 2020-04-25 17:39:33.486452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967f8a6f84a6'
down_revision = '9c9ab138c396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.drop_column('master', 'fist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('fist_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('master', 'first_name')
    # ### end Alembic commands ###
