"""Schedule Change added time

Revision ID: 9c9ab138c396
Revises: e4c9f64617ff
Create Date: 2020-04-22 17:10:25.455665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9ab138c396'
down_revision = 'e4c9f64617ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_change', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('schedule_change', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_change', 'start_time')
    op.drop_column('schedule_change', 'end_time')
    # ### end Alembic commands ###
