"""procedure relevant not nullable

Revision ID: a00001656e97
Revises: 09683593d228
Create Date: 2020-06-10 18:08:54.001525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00001656e97'
down_revision = '09683593d228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedure', 'is_relevant',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedure', 'is_relevant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
