"""Added nullable password

Revision ID: c5007c2e3099
Revises: 75dc13d4b110
Create Date: 2020-05-18 21:46:55.245680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5007c2e3099'
down_revision = '75dc13d4b110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'password')
    # ### end Alembic commands ###
