"""Appointment Paint PaintSupply AP

Revision ID: d8c159f541eb
Revises: 69379fc40c85
Create Date: 2020-04-22 16:28:33.145347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c159f541eb'
down_revision = '69379fc40c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('left_ml', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('paint_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paint_id'], ['paint.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appoint_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('preferences', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_time', 'client_id', name='unique_client_time'),
    sa.UniqueConstraint('start_time', 'master_id', name='unique_master_time')
    )
    op.create_table('appointment_paint',
    sa.Column('volume_ml', sa.Integer(), nullable=False),
    sa.Column('paint_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paint_id'], ['paint.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('paint_id', 'appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_paint')
    op.drop_table('appointment')
    op.drop_table('paint_supply')
    op.drop_table('paint')
    # ### end Alembic commands ###
