"""Schedule Change only date

Revision ID: e4c9f64617ff
Revises: d8c159f541eb
Create Date: 2020-04-22 17:09:46.222949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4c9f64617ff'
down_revision = 'd8c159f541eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_change', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('schedule_change', sa.Column('start_date', sa.Date(), nullable=False))
    op.drop_column('schedule_change', 'end_time')
    op.drop_column('schedule_change', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_change', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('schedule_change', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('schedule_change', 'start_date')
    op.drop_column('schedule_change', 'end_date')
    # ### end Alembic commands ###
