"""Separate data and time schedule

Revision ID: e8c69831d42b
Revises: 6d3956699398
Create Date: 2020-05-02 07:52:52.499486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8c69831d42b'
down_revision = '6d3956699398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_change', sa.Column('change_end', sa.DateTime(), nullable=False))
    op.add_column('schedule_change', sa.Column('change_start', sa.DateTime(), nullable=False))
    op.drop_column('schedule_change', 'start_time')
    op.drop_column('schedule_change', 'end_date')
    op.drop_column('schedule_change', 'end_time')
    op.drop_column('schedule_change', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_change', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('schedule_change', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('schedule_change', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('schedule_change', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('schedule_change', 'change_start')
    op.drop_column('schedule_change', 'change_end')
    # ### end Alembic commands ###
